### ISSUE TITLE
Revise title

### ISSUE THREAD

**Issue by JJ** [NuriaStatgirl/ComparingOptimizationMethods#2]
Check that the new title is correct.

**Comment by JJ** [comment]
It would be convenient that you would start addressing these issues...

**Comment by mgarenas** [comment]
For me it will be impossible for this weekend, May be, we have to think 
about another deadline.

maribel

**Comment by JJ** [comment]
We could get back to this, starting by the title.

**Comment by JJ** [comment]
Once again, can we get back to this? Shoot for a journal paper?

**Comment by mgarenas** [comment]
Sure, I've collect all the suggestions of Pedro and I'll push to the 
repo soon. Now I'm involved with others things, but I'll recopilate all 
your suggestions for the next version. Please be concrete with the 
suggestions, do not write open subjects because it will be complicated 
to carry out them.

Maribel
On 09/04/15 10:38, Juan Julián Merelo Guervós wrote:

> Once again, can we get back to this? Shoot for a journal paper?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NuriaStatgirl/ComparingOptimizationMethods/issues/2#issuecomment-91151264.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada
